apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: testdonet05062025-gitops
  description: This is GitOps manifest for testdonet05062025   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=testdonet05062025
    backstage.io/kubernetes-id: testdonet05062025 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: testdonet05062025
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:testdonet05062025
