apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: testdonet05062025
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/quay_xjiang/testdonet05062025:dc3cbd43210fdec1e09a1a7e56ddc6a44fe3e096@sha256:c6187394709db79f068e84ec86cfee0ecfc22b1590a824c3276eb0391ab1b28b
          name: container-image
