apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: testdonet05062025
  janus-idp.io/tekton: testdonet05062025
  backstage.io/kubernetes-id: testdonet05062025
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: testdonet05062025
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
