apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: testdonet05062025
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testdonet05062025 
  name: testdonet05062025
spec:
  port:
    targetPort: 3001 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: testdonet05062025
    weight: 100 
